whitelist:
  origins:
    - alorel.github.io
  targets:
    - github.com

github:
  user: Alorel
  api_key_env: GH_API_KEY

env:
  whitelist:
    origins: ADDITIONAL_WHITELIST_ORIGINS
    targets: ADDITIONAL_WHITELIST_TARGETS

blank_response_origins:
  - alorel-http-proxy.herokuapp.com

default_port: 5000
cache_time: 300000

headers:
  Access-Control-Allow-Methods: GET
  Access-Control-Allow-Credentials: "false"
  Cache-Control: no-cache, no-store
  X-Content-Type-Options: nosniff
  X-Download-Options: noopen
  X-Frame-Options: deny
  X-XSS-Protection: 1; mode=block
  X-Powered-By: Trump's tiny cocktail sausage fingers
  X-source-code: https://github.com/Alorel/node-cors-server

shrinkray:
  threshold: 1
  zlib:
    level: 9
  brotli:
    quality: 11

htmlmin:
  cssmin: true
  jsmin: true
  removeComments: true
  collapseWhitespace: true
  removeOptionalTags: true
